export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type_file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns, hooks, and component structures",
    isFavorite: true,
    itemCount: 24,
    createdAt: new Date("2026-01-10T08:00:00Z"),
    updatedAt: new Date("2026-04-01T12:00:00Z"),
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Curated prompts for coding assistants and GPT",
    isFavorite: true,
    itemCount: 18,
    createdAt: new Date("2026-01-15T09:00:00Z"),
    updatedAt: new Date("2026-04-05T10:00:00Z"),
  },
  {
    id: "col_3",
    name: "Shell Scripts",
    description: "Useful bash commands and scripts",
    isFavorite: false,
    itemCount: 12,
    createdAt: new Date("2026-02-01T10:00:00Z"),
    updatedAt: new Date("2026-03-20T14:00:00Z"),
  },
  {
    id: "col_4",
    name: "Project Ideas",
    description: "Notes and brainstorms for side projects",
    isFavorite: false,
    itemCount: 31,
    createdAt: new Date("2026-02-10T11:00:00Z"),
    updatedAt: new Date("2026-04-08T09:00:00Z"),
  },
  {
    id: "col_5",
    name: "Dev Resources",
    description: "Useful links and documentation bookmarks",
    isFavorite: false,
    itemCount: 45,
    createdAt: new Date("2026-02-20T08:00:00Z"),
    updatedAt: new Date("2026-04-07T16:00:00Z"),
  },
  {
    id: "col_6",
    name: "API Examples",
    description: "REST and GraphQL API patterns",
    isFavorite: false,
    itemCount: 15,
    createdAt: new Date("2026-03-01T10:00:00Z"),
    updatedAt: new Date("2026-04-06T11:00:00Z"),
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useDebounce Hook",
    description: null,
    contentType: "TEXT" as const,
    content:
      "function useDebounce<T>(value: T, delay: number) {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n  // ...\n}",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-09T10:00:00Z"),
    itemTypeId: "type_snippet",
    itemType: { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
    createdAt: new Date("2026-03-01T08:00:00Z"),
    updatedAt: new Date("2026-04-09T10:00:00Z"),
  },
  {
    id: "item_2",
    title: "Code Review Prompt",
    description: null,
    contentType: "TEXT" as const,
    content:
      "Review this code for:\n1. Performance issues\n2. Security vulnerabilities\n3. Best practices",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-09T09:00:00Z"),
    itemTypeId: "type_prompt",
    itemType: { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
    createdAt: new Date("2026-03-05T09:00:00Z"),
    updatedAt: new Date("2026-04-09T09:00:00Z"),
  },
  {
    id: "item_3",
    title: "Docker Cleanup",
    description: null,
    contentType: "TEXT" as const,
    content:
      "# Remove all stopped containers\ndocker container prune -f\n# Remove unused images\ndocker image prune -a -f",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-08T15:00:00Z"),
    itemTypeId: "type_command",
    itemType: { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
    createdAt: new Date("2026-02-15T10:00:00Z"),
    updatedAt: new Date("2026-04-08T15:00:00Z"),
  },
  {
    id: "item_4",
    title: "Next.js 16 Features",
    description: null,
    contentType: "TEXT" as const,
    content: "## Key Changes in Next.js 16\n- Turbopack is now default...",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-08T12:00:00Z"),
    itemTypeId: "type_note",
    itemType: { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
    createdAt: new Date("2026-03-20T11:00:00Z"),
    updatedAt: new Date("2026-04-08T12:00:00Z"),
  },
  {
    id: "item_5",
    title: "Tailwind CSS Docs",
    description: null,
    contentType: "URL" as const,
    url: "https://tailwindcss.com/docs",
    language: null,
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date("2026-04-07T10:00:00Z"),
    itemTypeId: "type_link",
    itemType: { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
    createdAt: new Date("2026-01-20T08:00:00Z"),
    updatedAt: new Date("2026-04-07T10:00:00Z"),
  },
  {
    id: "item_6",
    title: "Zod Schema Validator",
    description: null,
    contentType: "TEXT" as const,
    content:
      "import { z } from 'zod';\n\nconst schema = z.object({\n  email: z.string().email(),\n  age: z.number().min(18),\n});",
    language: "typescript",
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date("2026-04-06T08:00:00Z"),
    itemTypeId: "type_snippet",
    itemType: { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
    createdAt: new Date("2026-02-10T09:00:00Z"),
    updatedAt: new Date("2026-04-06T08:00:00Z"),
  },
  {
    id: "item_7",
    title: "Git Branch Cleanup",
    description: null,
    contentType: "TEXT" as const,
    content: "git branch --merged | grep -v '\\*\\|main\\|master' | xargs git branch -d",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-05T14:00:00Z"),
    itemTypeId: "type_command",
    itemType: { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
    createdAt: new Date("2026-01-25T13:00:00Z"),
    updatedAt: new Date("2026-04-05T14:00:00Z"),
  },
  {
    id: "item_8",
    title: "System Prompt Template",
    description: null,
    contentType: "TEXT" as const,
    content:
      "You are a helpful assistant specialized in {{domain}}. Always respond in {{language}}. Format code in markdown.",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date("2026-04-04T11:00:00Z"),
    itemTypeId: "type_prompt",
    itemType: { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
    createdAt: new Date("2026-03-10T10:00:00Z"),
    updatedAt: new Date("2026-04-04T11:00:00Z"),
  },
];

// Item counts per type (for sidebar)
export const mockItemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 12,
  type_note: 31,
  type_link: 45,
  type_file: 8,
  type_image: 5,
};